// Swedish translations, keyed by the English text (see i18n.ts). Chess terms follow Swedish chess usage:
// bonde, springare, löpare, torn, dam, kung; gaffel, bindning, spett, avtäckt angrepp.
export const SV: Record<string, string> = {
  // ---- Pieces ----
  pawn: 'bonde',
  knight: 'springare',
  bishop: 'löpare',
  rook: 'torn',
  queen: 'dam',
  king: 'kung',
  'the pawn': 'bonden',
  'the knight': 'springaren',
  'the bishop': 'löparen',
  'the rook': 'tornet',
  'the queen': 'damen',
  'the king': 'kungen',
  'a pawn': 'en bonde',
  'a knight': 'en springare',
  'a bishop': 'en löpare',
  'a rook': 'ett torn',
  'a queen': 'en dam',
  'a king': 'en kung',

  // ---- Tactics ----
  'mating attack': 'mattangrepp',
  'back-rank mate': 'baklinjematt',
  'free piece': 'fri pjäs',
  fork: 'gaffel',
  pin: 'bindning',
  skewer: 'spett',
  'discovered attack': 'avtäckt angrepp',
  combination: 'kombination',
  '{what} on {square}': '{what} på {square}',
  'a free piece': 'en fri pjäs',
  'a free pawn': 'en fri bonde',
  'a free knight': 'en fri springare',
  'a free bishop': 'en fri löpare',
  'a free rook': 'ett fritt torn',
  'a free queen': 'en fri dam',
  'a fork': 'en gaffel',
  'a pawn fork': 'en bondegaffel',
  'a knight fork': 'en springargaffel',
  'a bishop fork': 'en löpargaffel',
  'a rook fork': 'en torngaffel',
  'a queen fork': 'en damgaffel',
  'a king fork': 'en kungsgaffel',
  'a pin': 'en bindning',
  'a skewer': 'ett spett',
  'a {piece} pin of {target}': 'en bindning av {target} med {pieceThe}',
  'a {piece} skewer of {target}': 'ett spett mot {target} med {pieceThe}',
  'a discovered attack': 'ett avtäckt angrepp',
  'a discovered attack on {target}': 'ett avtäckt angrepp mot {target}',
  'a mating attack': 'ett mattangrepp',
  'a back-rank mate': 'en baklinjematt',
  'a combination': 'en kombination',

  // ---- Engine lines (analysis.ts) ----
  'allows mate': 'tillåter matt',
  'misses mate': 'missar matt',
  'This line allows a forced mate': 'Den här varianten tillåter forcerad matt',
  'The best line forces mate; this one does not': 'Bästa varianten tvingar fram matt, den här gör det inte',
  'As good as the best line': 'Lika bra som bästa varianten',
  '{n} pawns worse than the best line': '{n} bönder sämre än bästa varianten',
  rapid: 'snabbschack',
  blitz: 'blixt',
  bullet: 'bullet',
  daily: 'daglig',
  classical: 'klassiskt',

  // ---- Explanations (explain.ts) ----
  "a queen's worth of material": 'material motsvarande en dam',
  'a piece and a pawn': 'en pjäs och en bonde',
  'a piece': 'en pjäs',
  "two pawns' worth of material": 'material motsvarande två bönder',
  White: 'Vit',
  Black: 'Svart',
  'winning for {side}': 'vinnande för {side}',
  'about equal': 'ungefär jämnt',
  'slightly better for {side}': 'något bättre för {side}',
  'clearly better for {side}': 'klart bättre för {side}',
  'a best move': 'ett bästa drag',
  'a good move': 'ett bra drag',
  'an inaccuracy': 'en felaktighet',
  'a mistake': 'ett misstag',
  'a blunder': 'en blunder',
  'another move': 'ett annat drag',
  'This allows {opponent} to force mate in {n}: {line}.': 'Det här låter {opponent} tvinga fram matt i {n}: {line}.',
  '{mover} had a forced mate in {n} starting with {move}: {line}.': '{mover} hade forcerad matt i {n} med {move}: {line}.',
  'This loses {material} {swing}. {opponent} answers {line}.': 'Det här förlorar {material} {swing}. {opponent} svarar {line}.',
  'This misses a chance to win {material} with {move} {swing}: {line}.': 'Det här missar chansen att vinna {material} med {move} {swing}: {line}.',
  'The position goes from {from} to {to} {swing}. {move} was stronger: {line}.':
    'Ställningen går från {from} till {to} {swing}. {move} var starkare: {line}.',
  '{before} ({beforeScore}) instead of {after} ({afterScore}) after {played}': '{before} ({beforeScore}) i stället för {after} ({afterScore}) efter {played}',
  'keeps the position {outcome}': 'behåller ställningen {outcome}',
  'limits the damage: {outcome}': 'begränsar skadan: {outcome}',
  '{move} forces mate in {n}: {line}.': '{move} tvingar fram matt i {n}: {line}.',
  '{move} wins {material} and {keeps}: {line}.': '{move} vinner {material} och {keeps}: {line}.',
  'gives up less material': 'ger bort mindre material',
  'avoids losing material': 'undviker att förlora material',
  '{move} {saves} and {keeps}: {line}.': '{move} {saves} och {keeps}: {line}.',
  '{move} {keeps}: {line}.': '{move} {keeps}: {line}.',
  opening: 'öppning',
  middlegame: 'mittspel',
  endgame: 'slutspel',
  Excellent: 'Utmärkt',
  Good: 'Bra',
  Inaccurate: 'Ojämn',
  Poor: 'Svag',
  ' in the {opening}': ' i {opening}',
  "with {pct} accuracy against {loser}'s {loserPct}": 'med {pct} precision mot {loser}s {loserPct}',
  'despite lower accuracy ({pct} vs {loserPct})': 'trots lägre precision ({pct} mot {loserPct})',
  '{winner} won{inOpening} {verdict}.': '{winner} vann{inOpening} {verdict}.',
  'The game is unfinished': 'Partiet är inte avslutat',
  'The game was drawn': 'Partiet slutade remi',
  '{outcome}{inOpening}. Accuracy: {white} {whitePct}, {black} {blackPct}.': '{outcome}{inOpening}. Precision: {white} {whitePct}, {black} {blackPct}.',
  '{name} took a decisive advantage after {move} and never let it go.': '{name} tog ett avgörande övertag efter {move} och släppte det aldrig.',
  'The game was decided by the very last move.': 'Partiet avgjordes av det allra sista draget.',
  'The final position was not yet decisive, so the game was likely decided on time.':
    'Slutställningen var ännu inte avgjord, så partiet avgjordes troligen på tid.',
  'The turning point was {move}, {label} that cost {name} about {n}% winning chances.':
    'Vändpunkten var {move}, {label} som kostade {name} ungefär {n}% i vinstchans.',

  // ---- My patterns (patterns.ts) ----
  '{move} vs {opponent}': '{move} mot {opponent}',
  '{n} s left on the clock': '{n} s kvar på klockan',
  'Allowed {tactic}': 'Tillät {tactic}',
  '{move} was winning{how}': '{move} vann{how}',
  'Mate in {n} with {move}': 'Matt i {n} med {move}',
  'Was winning ({n}%), then this': 'Vinnande ({n}%), sedan det här',
  '{n} time': '{n} gång',
  '{n} times': '{n} gånger',
  '{times} in {games} games': '{times} på {games} partier',
  '{n} game': '{n} parti',
  '{n} games': '{n} partier',
  '{n} moves': '{n} drag',
  'You leave pieces hanging': 'Du lämnar pjäser hängande',
  'A piece of yours was simply taken for free, most often {piece} ({k}×). Before each move, check what your opponent can capture.':
    'En av dina pjäser togs helt gratis, oftast {piece} ({k}×). Kolla före varje drag vad motståndaren kan slå.',
  'You walk into forks': 'Du går in i gafflar',
  'Your opponent attacked two of your pieces at once, mostly with {piece}. Watch for squares where one enemy piece could hit two of yours, especially king and queen.':
    'Motståndaren angrep två av dina pjäser samtidigt, oftast med {piece}. Se upp för fält där en motståndarpjäs kan träffa två av dina, särskilt kung och dam.',
  'Pins and skewers cost you material': 'Bindningar och spett kostar dig material',
  'Pieces lined up with your king or queen got pinned or skewered by a bishop, rook or queen. Avoid leaving valuable pieces on the same line.':
    'Pjäser som stod på linje med din kung eller dam blev bundna eller spetsade av en löpare, ett torn eller en dam. Undvik att ställa värdefulla pjäser på samma linje.',
  'Discovered attacks catch you out': 'Avtäckta angrepp överraskar dig',
  "An enemy piece moved out of the way and uncovered an attack from the piece behind it. Look at what's lined up behind your opponent's pieces, not just the pieces themselves.":
    'En motståndarpjäs flyttade undan och avtäckte ett angrepp från pjäsen bakom. Titta på vad som står bakom motståndarens pjäser, inte bara på pjäserna själva.',
  'You walk into mating attacks': 'Du går in i mattangrepp',
  'A move of yours allowed a forced mate, {n} of them on your back rank (give your king an escape square, e.g. a pawn move like h3).':
    'Ett av dina drag tillät forcerad matt, {n} av dem på din baklinje (ge kungen en flyktruta, t.ex. med ett bondedrag som h3).',
  'A move of yours allowed a forced mate.': 'Ett av dina drag tillät forcerad matt.',
  "You don't punish your opponents' mistakes": 'Du straffar inte motståndarens misstag',
  "Your opponent's move gave you a clearly better position {chances}; you kept the advantage {taken} ({pct}%).":
    'Motståndarens drag gav dig en klart bättre ställning {chances}; du behöll fördelen {taken} ({pct}%).',
  ' The win you missed was most often {tactic}.': ' Vinsten du missade var oftast {tactic}.',
  ' After every opponent move, ask what it left undefended.': ' Fråga dig efter varje motståndardrag vad det lämnade oskyddat.',
  '{missed} missed out of {chances} chances in {games} games': '{missed} missade av {chances} chanser på {games} partier',
  'Time trouble costs you': 'Tidsnöd kostar dig',
  '{pct}% of your mistakes came when you were low on time, where you err {x}× as often as usual. Spend less time early so you have some left at the end.':
    '{pct}% av dina misstag kom när du hade ont om tid, då du gör fel {x}× så ofta som annars. Lägg mindre tid tidigt så att du har kvar i slutet.',
  '{errors} mistakes in {moves} low-time moves': '{errors} misstag på {moves} drag i tidsnöd',
  'You let winning positions slip': 'Du släpper vinnande ställningar',
  "You had a winning position and didn't win. When you're ahead, slow down: trade pieces and keep everything protected.":
    'Du hade en vinnande ställning men vann inte. När du leder, ta det lugnt: byt av pjäser och håll allt skyddat.',
  '{k} of {games} games': '{k} av {games} partier',
  'You miss checkmates': 'Du missar matter',
  "You had a short forced mate and didn't play it. Always look at checks first: they're the most forcing moves.":
    'Du hade en kort forcerad matt men spelade den inte. Titta alltid på schackar först: de är de mest forcerande dragen.',
  'the opening': 'öppningen',
  'the middlegame': 'mittspelet',
  'the endgame': 'slutspelet',
  'Most of your mistakes happen in {phase}': 'De flesta av dina misstag sker i {phase}',
  'In positions that were still undecided, you make {worst} mistakes per 100 moves in {worstPhase}, against {best} in {bestPhase}.':
    'I ställningar som ännu inte var avgjorda gör du {worst} misstag per 100 drag i {worstPhase}, mot {best} i {bestPhase}.',
  '{worstMoves} moves in {worstPhase} and {bestMoves} in {bestPhase}': '{worstMoves} drag i {worstPhase} och {bestMoves} i {bestPhase}',
  'Your strongest phase is {phase}': 'Din starkaste fas är {phase}',
  'In undecided positions: {acc}% accuracy and {errors} mistakes per 100 moves.': 'I oavgjorda ställningar: {acc}% precision och {errors} misstag per 100 drag.',
  '{opening} is a weak spot': '{opening} är en svag punkt',
  'As {color} you scored {pct}% in the {opening}. Worth looking up its main ideas.': 'Som {color} tog du {pct}% av poängen i {opening}. Värt att läsa på om huvudidéerna.',
  'You do well in the {opening}': 'Det går bra för dig i {opening}',
  'As {color} you scored {pct}%.': 'Som {color} tog du {pct}% av poängen.',
  "You're improving": 'Du blir bättre',
  'Your recent games were weaker': 'Dina senaste partier var svagare',
  'Your level is steady': 'Din nivå är stabil',
  'Your last {half} games: {accNew}% accuracy and {errNew} mistakes per game, against {accOld}% and {errOld} in the {half} before.':
    'Dina senaste {half} partier: {accNew}% precision och {errNew} misstag per parti, mot {accOld}% och {errOld} i de {half} innan.',
  'Unknown opening': 'Okänd öppning',

  // ---- Puzzles (puzzles.ts) ----
  'Your opponent just made a mistake. Find the move that punishes it.': 'Motståndaren gjorde just ett misstag. Hitta draget som straffar det.',
  'You went wrong here in the game. Find a better move.': 'Här gick det fel i partiet. Hitta ett bättre drag.',
  'Look for {tactic}.': 'Leta efter {tactic}.',
  'In the game, {played} allowed {tactic}. Look for a safer move.': 'I partiet tillät {played} {tactic}. Leta efter ett säkrare drag.',
  'Check every capture, check and threat for both sides first.': 'Gå först igenom alla slag, schackar och hot för båda sidor.',
  'takes {piece} on {square}': 'slår {piece} på {square}',
  'gives checkmate': 'ger schackmatt',
  'gives check': 'ger schack',
  '{piece} on {square}': '{piece} på {square}',
  'attacks {targets}': 'angriper {targets}',
  ' and ': ' och ',
  'uncovers an attack by {attacker} on {target} on {square}': 'avtäcker ett angrepp med {attacker} mot {target} på {square}',
  '{opponent} had just played {move}, {label} ({was})': '{opponent} hade just spelat {move}, {label} ({was})',
  '; {move} was needed.': '; {move} behövdes.',
  ' It left {piece} on {square} undefended.': ' Det lämnade {piece} på {square} utan skydd.',

  // ---- Analysis screen (App.tsx) ----
  'Best move': 'Bästa draget',
  'Good move': 'Bra drag',
  Inaccuracy: 'Felaktighet',
  Mistake: 'Misstag',
  Blunder: 'Blunder',
  'Review engine failed to start: {error}': 'Granskningsmotorn kunde inte starta: {error}',
  'Full engine failed to start: {error}': 'Den fullständiga motorn kunde inte starta: {error}',
  'Lite engine failed to start: {error}': 'Lite-motorn kunde inte starta: {error}',
  'Deep analysis engine failed to start: {error}': 'Motorn för djupanalys kunde inte starta: {error}',
  'Could not read that PGN: {error}': 'Kunde inte läsa PGN: {error}',
  'Estimated rating for this game, compared with {basis} players': 'Uppskattad rating för partiet, jämfört med spelare i {basis}',
  ' (game too short to be reliable)': ' (för kort parti för att vara tillförlitligt)',
  ' (rough: single fast games vary a lot)': ' (grovt: enskilda snabba partier varierar mycket)',
  'Alternate line': 'Sidovariant',
  '{move}: how {opponent} can punish it': '{move}: så kan {opponent} straffa det',
  'What {player} could have played instead of {move}': 'Vad {player} kunde ha spelat i stället för {move}',
  Puzzles: 'Problem',
  'My patterns': 'Mina mönster',
  Patterns: 'Mönster',
  'Flip board (f)': 'Vänd brädet (f)',
  'Flip board': 'Vänd brädet',
  Flip: 'Vänd',
  'Load game': 'Ladda parti',
  Start: 'Början',
  Back: 'Bakåt',
  Forward: 'Framåt',
  End: 'Slutet',
  'Engine problem.': 'Problem med motorn.',
  'Page is cross-origin isolated': 'Sidan är cross-origin-isolerad',
  'Page is not cross-origin isolated': 'Sidan är inte cross-origin-isolerad',
  Reload: 'Ladda om',
  'Reviewing game… {done}/{total}': 'Granskar partiet… {done}/{total}',
  'best was {move}': 'bäst var {move}',
  'Show why': 'Visa varför',
  'Show best': 'Visa bästa',
  'Game over': 'Partiet är slut',
  'Stockfish 19 · depth {depth}': 'Stockfish 19 · djup {depth}',
  'Engine thinking…': 'Motorn tänker…',
  'Live engine': 'Motor',
  'Small network, instant': 'Litet nätverk, direkt',
  'Full Stockfish 19 network (~99 MB download once), multi-threaded': 'Fullständigt Stockfish 19-nätverk (~99 MB, laddas ned en gång), flertrådat',
  Summary: 'Sammanfattning',
  Moves: 'Drag',

  // ---- Import panel ----
  'My games': 'Mina partier',
  'Paste PGN': 'Klistra in PGN',
  Username: 'Användarnamn',
  Fetch: 'Hämta',
  'No games found.': 'Inga partier hittades.',
  'Enter your username to list recent games, or': 'Ange ditt användarnamn för att lista dina senaste partier, eller',
  'try a sample game': 'prova ett exempelparti',
  'Paste a PGN…': 'Klistra in en PGN…',
  Analyze: 'Analysera',
  'Try a sample game': 'Prova ett exempelparti',

  // ---- Summary card ----
  'Average centipawn loss {n}': 'Genomsnittlig centibondeförlust {n}',
  'Played like ~{n}': 'Spelade som ~{n}',
  'rated {n}': 'rating {n}',
  'vs {basis} players': 'jämfört med spelare i {basis}',
  '{basis} equivalent (no calibration for this game type)': 'motsvarande {basis} (ingen kalibrering för den här partitypen)',
  ' · rough: single fast games vary a lot': ' · grovt: enskilda snabba partier varierar mycket',
  inaccuracy: 'felaktighet',
  mistake: 'misstag',
  blunder: 'blunder',
  'Key moments': 'Viktiga ögonblick',
  'Deep analysis · full Stockfish 19': 'Djupanalys · fullständig Stockfish 19',
  'Deep analysis… {done}/{total}': 'Djupanalys… {done}/{total}',
  ' · about {time} left': ' · cirka {time} kvar',
  'Deep analysis': 'Djupanalys',
  'Re-check every move with the full engine (takes a few minutes)': 'Kontrollera varje drag med den fullständiga motorn (tar några minuter)',

  // ---- Side-line banner and engine lines ----
  'Side line': 'Sidovariant',
  "Why it's bad": 'Därför är det dåligt',
  'Better move': 'Bättre drag',
  'Back to game': 'Tillbaka till partiet',
  'Start of line': 'Variantens början',
  'As good as the best move': 'Lika bra som bästa draget',
  'Slightly worse than the best move': 'Något sämre än bästa draget',
  'Inaccuracy compared with the best move': 'Felaktighet jämfört med bästa draget',
  'Mistake compared with the best move': 'Misstag jämfört med bästa draget',
  'Blunder compared with the best move': 'Blunder jämfört med bästa draget',
  'Best line': 'Bästa varianten',

  // ---- My patterns screen ----
  Rapid: 'Snabbschack',
  Blitz: 'Blixt',
  Bullet: 'Bullet',
  Classical: 'Klassiskt',
  Daily: 'Dagligt',
  All: 'Alla',
  'Reviews your recent games and looks for mistakes you keep making. Each game is analyzed once and kept in this browser.':
    'Granskar dina senaste partier och letar efter misstag du gör om och om igen. Varje parti analyseras en gång och sparas i den här webbläsaren.',
  'Last {n}': 'Senaste {n}',
  Stop: 'Stoppa',
  'Analyze my games': 'Analysera mina partier',
  'No reviewed games for this player yet.': 'Inga granskade partier för den här spelaren än.',
  'Fetching games…': 'Hämtar partier…',
  'Stopped. Games reviewed so far are kept.': 'Stoppad. Partier som redan granskats sparas.',
  'Done: {total} games ({done} newly reviewed, {cached} from earlier).': 'Klart: {total} partier ({done} nyss granskade, {cached} sedan tidigare).',
  'Reviewing {done}/{todo} new games with {n} engine': 'Granskar {done}/{todo} nya partier med {n} motor',
  'Reviewing {done}/{todo} new games with {n} engines': 'Granskar {done}/{todo} nya partier med {n} motorer',
  ' · {n} already reviewed': ' · {n} redan granskade',
  games: 'partier',
  'won/drawn/lost': 'vinst/remi/förlust',
  'avg accuracy': 'snittprecision',
  'plays like': 'spelar som',
  'No recurring problems found in these games. Nice!': 'Inga återkommande problem i de här partierna. Snyggt!',
  Tactics: 'Taktik',
  "What your opponents' best reply did after your mistakes, and what you could have played when they erred.":
    'Vad motståndarens bästa svar gjorde efter dina misstag, och vad du kunde ha spelat när de gjorde fel.',
  'Used against you': 'Använt mot dig',
  'You missed': 'Du missade',
  'By phase': 'Per fas',
  "Only positions that were still undecided, so won or lost endgames don't skew it.":
    'Bara ställningar som ännu inte var avgjorda, så att vunna eller förlorade slutspel inte snedvrider siffrorna.',
  'Your moves': 'Dina drag',
  'Mistakes /100': 'Misstag /100',
  Accuracy: 'Precision',
  Openings: 'Öppningar',
  Games: 'Partier',
  Score: 'Poäng',
  'By colour': 'Per färg',
  'Based on little data; analyze more games to confirm': 'Bygger på lite data; analysera fler partier för att bekräfta',
  tentative: 'preliminärt',
  'Based on {evidence}': 'Baserat på {evidence}',

  // ---- Puzzle screen ----
  'Correct! {move} is the best move.': 'Rätt! {move} är bästa draget.',
  'Checking your move…': 'Kontrollerar ditt drag…',
  "Good move! {move} works too. The engine's top choice was {best}.": 'Bra drag! {move} fungerar också. Motorns förstaval var {best}.',
  'Not quite. After {move}, your opponent can answer {reply}. Try again.': 'Inte riktigt. Efter {move} kan motståndaren svara {reply}. Försök igen.',
  strongly: 'starkt',
  'The answer was {move}.': 'Svaret var {move}.',
  'Puzzles are made from your own games. Analyze your games in My patterns first.': 'Problemen skapas från dina egna partier. Analysera först dina partier under Mina mönster.',
  'Go to My patterns': 'Gå till Mina mönster',
  'Loading puzzles…': 'Laddar problem…',
  'No puzzles yet for {user}. Analyze some games in My patterns, and your mistakes become puzzles here.':
    'Inga problem än för {user}. Analysera några partier under Mina mönster så blir dina misstag problem här.',
  Train: 'Träna',
  'All puzzles ({n})': 'Alla problem ({n})',
  'Daily goal: {n} puzzles solved': 'Dagsmål: {n} lösta problem',
  '🎯 Daily goal done!': '🎯 Dagsmålet klart!',
  'Today {n}/{goal}': 'Idag {n}/{goal}',
  'Days in a row with at least one solved puzzle': 'Dagar i rad med minst ett löst problem',
  '{n} day': '{n} dag',
  '{n} days': '{n} dagar',
  '{n} in a row': '{n} i rad',
  '{due} due · {fresh} new · {mastered} mastered': '{due} att repetera · {fresh} nya · {mastered} behärskade',
  ' · this session {solved}/{tried}': ' · den här gången {solved}/{tried}',
  ' · best run {n}': ' · bästa svit {n}',
  'All caught up': 'Allt klart för nu',
  'No puzzles are due right now. Analyze more games to get new ones, or come back later.':
    'Inga problem att repetera just nu. Analysera fler partier för att få nya, eller kom tillbaka senare.',
  'Practice anyway': 'Träna ändå',
  'White to move': 'Vit vid draget',
  'Black to move': 'Svart vid draget',
  'Punish the mistake': 'Straffa misstaget',
  'Find a better move': 'Hitta ett bättre drag',
  'The piece to move is highlighted.': 'Pjäsen som ska flyttas är markerad.',
  'Why it works': 'Därför fungerar det',
  'Line: {line}': 'Variant: {line}',
  ' · In the game you played {move}.': ' · I partiet spelade du {move}.',
  Hint: 'Ledtråd',
  'Show solution': 'Visa lösningen',
  'Skip (→)': 'Hoppa över (→)',
  Skip: 'Hoppa över',
  'Next puzzle': 'Nästa problem',
  'Open game': 'Öppna partiet',
  New: 'Nytt',
  Due: 'Att repetera',
  Solved: 'Löst',
  Mastered: 'Behärskat',
  'All types': 'Alla typer',
  'All tactics': 'All taktik',
  'Any status': 'Alla statusar',
  'No puzzles match these filters.': 'Inga problem matchar filtren.',
  'avoid {tactic}': 'undvik {tactic}',
  Mastery: 'Behärskning',

  // ---- Live engine on/off ----
  Off: 'Av',
  'No live analysis (saves power)': 'Ingen liveanalys (sparar ström)',
  'Live analysis off · best line from the review': 'Liveanalys av · bästa varianten från granskningen',
  'Live analysis off': 'Liveanalys av',
  Paused: 'Pausad',
  'Paused · best line from the review': 'Pausad · bästa varianten från granskningen',
  'Best line from the review · engine starting…': 'Bästa varianten från granskningen · motorn startar…',
}
